__title__ = "mykiteconnect"
__description__ = "The unofficial Python client for the Kite Connect trading API"
__url__ = "https://kite.trade"
__download_url__ = "https://github.com/sangam/mykiteconnect"
__version__ = "5.0.1"
__author__ = "Sangam Chopade"
__license__ = "MIT"